### ISSUE TITLE
license on top of files? 

### ISSUE THREAD

**Issue by danyaljj** [IllinoisCogComp/lbjava#31]
@mssammon  @christos-c what do you think about adding this snippet on top of each file? 

```
/*******************************************************************************
 * University of Illinois/Research and Academic Use License 
 * Copyright (c) 2016, 
 *
 * Developed by:
 * The Cognitive Computations Group
 * University of Illinois at Urbana-Champaign
 * http://cogcomp.cs.illinois.edu/
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal with the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimers.
 * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimers in the documentation and/or other materials provided with the distribution.
 * Neither the names of the Cognitive Computations Group, nor the University of Illinois at Urbana-Champaign, nor the names of its contributors may be used to endorse or promote products derived from this Software without specific prior written permission.
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE CONTRIBUTORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS WITH THE SOFTWARE.
 *     
 *******************************************************************************/
```

**Comment by mssammon** [comment]
@danyaljj , where did you find this license text? This doesn't seem to be sufficiently clear about commercial use.  Take a look at the text of the license file that appears for e.g. nlp pipeline on our web site, which contains these paragraphs:

No license is granted herein that would permit Licensee to incorporate the Software into a commercial product, or to otherwise commercially exploit the Software. Should Licensee wish to make commercial use of the Software, Licensee should contact the University, c/o the Office of Technology Management ("OTM") to negotiate an appropriate license for such commercial use. To contact the OTM: otmmailaccount@ad.uiuc.edu; telephone: (217)333-3781;  fax: (217) 265-5530.
THE UNIVERSITY GIVES NO WARRANTIES, EITHER EXPRESSED OR IMPLIED, FOR THE SOFTWARE AND/OR ASSOCIATED MATERIALS PROVIDED UNDER THIS AGREEMENT, INCLUDING, WITHOUT LIMITATION, WARRANTY OF MERCHANTABILITY AND WARRANTY OF FITNESS FOR A PARTICULAR PURPOSE, AND ANY WARRANTY AGAINST INFRINGEMENT OF ANY INTELLECTUAL PROPERTY RIGHTS.

Licensee understands the Software is proprietary to the University. Licensee will take all reasonable steps to insure that the source code is protected and secured from unauthorized disclosure, use, or release and will treat it with at least the same level of care as Licensee would use to protect and secure its own proprietary computer programs and/or information, but using no less than reasonable care.

**Comment by danyaljj** [comment]
There is a [LICENSE](https://github.com/IllinoisCogComp/lbjava/blob/master/LICENSE) file in the root folder of the project which contains the complete Academic License. 

The snippet I have included here I found on top of files in SL.

**Comment by mssammon** [comment]
OK -- presumably we'll have to change the SL license too.  The snippet is more general than the actual A.U. license, so needs to change to reflect that. Perhaps:
```
/*******************************************************************************
 * This software is released under the University of Illinois/Research 
 *  and Academic Use License (see doc/LICENSE.txt for details). 
 * Copyright (c) 2016, 
 *
 * Developed by:
 * The Cognitive Computations Group
 * University of Illinois at Urbana-Champaign
 * http://cogcomp.cs.illinois.edu/
 *     
 *******************************************************************************/
```

**Comment by danr-ccg** [comment]
Yes, this piece of text seems good to me; plus a pointer to the U of I Academic License.
Thanks,
            Dan
